import type { TelemetryConfig } from './types';

export const DEFAULT_TELEMETRY_CONFIG: TelemetryConfig = {
  updateIntervalMs: 2000,
  seed: 42,
  modelMode: 'CALIBRATED',
};

export const MONITORING_BOUNDS = {
  minTemperatureC: 30.0,
  maxTemperatureC: 150.0,
  minViscosityCp: 10.0,
  maxViscosityCp: 50000.0,
  minMobilityDcP: 0.00001,
  maxMobilityDcP: 0.5,
  minProductionBopd: 0.0,
  maxProductionBopd: 100.0,
  minVfdHz: 30.0,
  maxVfdHz: 65.0,
  minSpm: 2.0,
  maxSpm: 15.0,
  minStrokeM: 1.0,
  maxStrokeM: 4.5,
  minSteamRateTpd: 0.0,
  maxSteamRateTpd: 250.0,
  maxLoadIndex: 85.0,
  maxRiskScore: 70.0,
};

export const REALTIME_DISCLAIMER =
  'PROTOTYPE SIMULATED TELEMETRY: All telemetry streams are generated by a deterministic mathematical simulation model for Baghewala Jodhpur Sandstone appraisal data (SPE 100642). Values reflect physical model dynamics, NOT live SCADA field measurements.';
