import type { CalibrationParameter } from './types';

export const CALIBRATION_DEFAULT_DISCLAIMER =
  'IMPORTANT PROVENANCE NOTICE: Calibrated parameters represent mathematical optimization outputs fitted against documented historical Baghewala appraisal data (SPE 100642). They are NOT direct downhole field measurements. Parameters lacking sufficient historical observations remain UNCALIBRATED (INSUFFICIENT_DATA) to prevent unvalidated curve-fitting.';

export const MIN_CALIBRATION_IMPROVEMENT_PERCENT = 1.0; // Minimum 1% error reduction required to accept calibration
export const EPSILON_SAFE_DIVISION = 1e-6;

export const INITIAL_CANDIDATE_PARAMETERS: CalibrationParameter[] = [
  {
    id: 'PARAM_PRODUCTIVITY_MOBILITY_COEFFICIENT',
    name: 'Productivity-Mobility Coefficient (C_prod)',
    category: 'production',
    value: 50.0,
    unit: 'BOPD/(bar·D/cP)',
    previousValue: 50.0,
    sourceType: 'derived',
    sourceId: 'SRC_ESTIMATION_04',
    calibrationStatus: 'ASSUMED',
    confidence: 'MEDIUM',
    minAllowed: 5.0,
    maxAllowed: 250.0,
    description: 'Empirical scaling factor converting Darcy oil mobility to Productivity Index (J_o). Evaluated against documented 2006 CSS pilot peak oil production snapshot.',
    calibratableReason: 'CALIBRATABLE — Documented 2006 CSS peak oil production rate (120 BOPD) enables deterministic parameter tuning.',
  },
  {
    id: 'PARAM_THERMAL_STEAM_GAIN_COEFFICIENT',
    name: 'Thermal Steam Gain Coefficient',
    category: 'thermal',
    value: 0.2,
    unit: '°C/(TPD·quality)',
    previousValue: 0.2,
    sourceType: 'derived',
    sourceId: 'SRC_ESTIMATION_04',
    calibrationStatus: 'NOT_CALIBRATABLE',
    confidence: 'LOW',
    minAllowed: 0.05,
    maxAllowed: 1.0,
    description: 'Reservoir heat transfer efficiency per unit steam enthalpy.',
    calibratableReason: 'NOT CALIBRATABLE — INSUFFICIENT HISTORICAL DATA: Downhole thermal log profiles during CSS soak phase are unmeasured in public Baghewala records.',
  },
  {
    id: 'PARAM_STEAM_EFFECTIVENESS_FACTOR',
    name: 'Steam Effectiveness Factor',
    category: 'css',
    value: 1.0,
    unit: 'factor',
    previousValue: 1.0,
    sourceType: 'derived',
    sourceId: 'SRC_ESTIMATION_04',
    calibrationStatus: 'NOT_CALIBRATABLE',
    confidence: 'LOW',
    minAllowed: 0.2,
    maxAllowed: 2.0,
    description: 'Fraction of injected steam enthalpy effective in heating heavy oil pay zone.',
    calibratableReason: 'NOT CALIBRATABLE — INSUFFICIENT HISTORICAL DATA: Continuous downhole steam quality and heat loss logs unavailable.',
  },
  {
    id: 'PARAM_SRP_LOAD_PENALTY_COEFFICIENT',
    name: 'SRP Dynamometer Load Penalty',
    category: 'srp',
    value: 1.0,
    unit: 'factor',
    previousValue: 1.0,
    sourceType: 'derived',
    sourceId: 'SRC_ESTIMATION_04',
    calibrationStatus: 'NOT_CALIBRATABLE',
    confidence: 'LOW',
    minAllowed: 0.5,
    maxAllowed: 3.0,
    description: 'Polished rod load strain multiplier under high viscosity fluid drag.',
    calibratableReason: 'NOT CALIBRATABLE — INSUFFICIENT HISTORICAL DATA: Measured downhole dynamometer cards unavailable in DGH records.',
  },
  {
    id: 'PARAM_EFFECTIVE_DRAWDOWN_COEFFICIENT',
    name: 'Effective Drawdown Pressure Coefficient',
    category: 'production',
    value: 30.0,
    unit: 'bar',
    previousValue: 30.0,
    sourceType: 'derived',
    sourceId: 'SRC_ESTIMATION_04',
    calibrationStatus: 'NOT_CALIBRATABLE',
    confidence: 'LOW',
    minAllowed: 5.0,
    maxAllowed: 80.0,
    description: 'Effective drawdown pressure differential maintained across perforation interval.',
    calibratableReason: 'NOT CALIBRATABLE — INSUFFICIENT HISTORICAL DATA: Dynamic bottomhole flowing pressure (Pwf) transient records unavailable.',
  },
];
