import type { UncertaintyParameter, UncertaintyConfiguration } from './types';

export const UNCERTAINTY_DISCLAIMER =
  'IMPORTANT PROVENANCE NOTICE: Uncertainty & Sensitivity analysis outputs are model-based Monte Carlo statistical estimates derived from configured parameter ranges. They are NOT field-certified forecasts or guarantees of actual Baghewala reservoir performance.';

export const DEFAULT_SAMPLE_COUNT = 500;
export const DEFAULT_SEED = 42;

export const DEFAULT_UNCERTAINTY_PARAMETERS: UncertaintyParameter[] = [
  {
    id: 'PARAM_PERMEABILITY',
    name: 'Reservoir Permeability (k)',
    unit: 'D',
    baselineValue: 2.5,
    minAllowed: 0.5,
    maxAllowed: 10.0,
    uncertaintyType: 'PERCENTAGE',
    uncertaintyValue: 25.0, // ±25%
    sourceType: 'documented',
    sourceId: 'SRC_OIL_PUB_01',
    isCalibrated: false,
    provenanceLabel: 'DOCUMENTED — Core Analysis (OIL India)',
    description: 'Pay sandstone permeability from core laboratory analysis.',
    category: 'reservoir',
  },
  {
    id: 'PARAM_RES_TEMP',
    name: 'Reservoir Temperature (T_res)',
    unit: '°C',
    baselineValue: 48.0,
    minAllowed: 40.0,
    maxAllowed: 65.0,
    uncertaintyType: 'ABSOLUTE_RANGE',
    uncertaintyValue: 4.0, // ±4°C
    sourceType: 'documented',
    sourceId: 'SRC_SPE_CSS_03',
    isCalibrated: false,
    provenanceLabel: 'DOCUMENTED — Well Log Record (SPE 100642)',
    description: 'Native static reservoir temperature prior to steam injection.',
    category: 'reservoir',
  },
  {
    id: 'PARAM_CRUDE_VISCOSITY',
    name: 'Native Crude Viscosity @ 48°C',
    unit: 'cP',
    baselineValue: 15000.0,
    minAllowed: 5000.0,
    maxAllowed: 35000.0,
    uncertaintyType: 'PERCENTAGE',
    uncertaintyValue: 20.0, // ±20%
    sourceType: 'documented',
    sourceId: 'SRC_SPE_CSS_03',
    isCalibrated: false,
    provenanceLabel: 'DOCUMENTED — Rheology Data (SPE 100642)',
    description: 'Baghewala heavy crude oil viscosity measured at initial formation temperature.',
    category: 'fluid',
  },
  {
    id: 'PARAM_STEAM_RATE',
    name: 'Steam Injection Rate',
    unit: 'TPD',
    baselineValue: 80.0,
    minAllowed: 0.0,
    maxAllowed: 250.0,
    uncertaintyType: 'PERCENTAGE',
    uncertaintyValue: 15.0, // ±15%
    sourceType: 'scenario',
    sourceId: 'SRC_SCENARIO_INPUT',
    isCalibrated: false,
    provenanceLabel: 'SCENARIO — Steam Generator Capacity',
    description: 'Operational steam injection rate per well.',
    category: 'thermal',
  },
  {
    id: 'PARAM_STEAM_TEMP',
    name: 'Steam Injection Temperature',
    unit: '°C',
    baselineValue: 300.0,
    minAllowed: 200.0,
    maxAllowed: 350.0,
    uncertaintyType: 'ABSOLUTE_RANGE',
    uncertaintyValue: 20.0, // ±20°C
    sourceType: 'derived',
    sourceId: 'SRC_ESTIMATION_04',
    isCalibrated: false,
    provenanceLabel: 'ASSUMED — Surface Boiler Enthalpy',
    description: 'Saturated steam temperature at injection head.',
    category: 'thermal',
  },
  {
    id: 'PARAM_STEAM_EFFECTIVENESS',
    name: 'Steam Effectiveness Factor',
    unit: 'factor',
    baselineValue: 1.0,
    minAllowed: 0.4,
    maxAllowed: 1.5,
    uncertaintyType: 'PERCENTAGE',
    uncertaintyValue: 20.0, // ±20%
    sourceType: 'derived',
    sourceId: 'SRC_ESTIMATION_04',
    isCalibrated: false,
    provenanceLabel: 'ASSUMED RANGE — NOT HISTORICALLY CALIBRATED',
    description: 'Fraction of steam enthalpy effective in heating heavy oil pay zone.',
    category: 'thermal',
  },
  {
    id: 'PARAM_THERMAL_GAIN_COEFF',
    name: 'Thermal Gain Coefficient',
    unit: '°C/(TPD·qual)',
    baselineValue: 0.2,
    minAllowed: 0.05,
    maxAllowed: 0.5,
    uncertaintyType: 'PERCENTAGE',
    uncertaintyValue: 25.0, // ±25%
    sourceType: 'derived',
    sourceId: 'SRC_ESTIMATION_04',
    isCalibrated: false,
    provenanceLabel: 'ASSUMED RANGE — NOT HISTORICALLY CALIBRATED',
    description: 'Reservoir thermal response scaling coefficient.',
    category: 'thermal',
  },
  {
    id: 'PARAM_DRAWDOWN',
    name: 'Effective Operating Drawdown',
    unit: 'bar',
    baselineValue: 30.0,
    minAllowed: 10.0,
    maxAllowed: 60.0,
    uncertaintyType: 'PERCENTAGE',
    uncertaintyValue: 20.0, // ±20%
    sourceType: 'derived',
    sourceId: 'SRC_ESTIMATION_04',
    isCalibrated: false,
    provenanceLabel: 'DERIVED — Wellbore Inflow Pressure Diff',
    description: 'Effective pressure differential maintained across perforation interval.',
    category: 'production',
  },
  {
    id: 'PARAM_VFD_FREQ',
    name: 'SRP VFD Frequency',
    unit: 'Hz',
    baselineValue: 50.0,
    minAllowed: 30.0,
    maxAllowed: 60.0,
    uncertaintyType: 'ABSOLUTE_RANGE',
    uncertaintyValue: 5.0, // ±5 Hz
    sourceType: 'documented',
    sourceId: 'SRC_DGH_INDIA_02',
    isCalibrated: false,
    provenanceLabel: 'DOCUMENTED — Electrical Drive Record (DGH)',
    description: 'Variable frequency drive operational speed.',
    category: 'srp',
  },
  {
    id: 'PARAM_SPM',
    name: 'Surface Pumping Speed',
    unit: 'SPM',
    baselineValue: 8.0,
    minAllowed: 2.0,
    maxAllowed: 14.0,
    uncertaintyType: 'ABSOLUTE_RANGE',
    uncertaintyValue: 1.5, // ±1.5 SPM
    sourceType: 'documented',
    sourceId: 'SRC_DGH_INDIA_02',
    isCalibrated: false,
    provenanceLabel: 'DOCUMENTED — Sucker Rod Pumping Record (DGH)',
    description: 'Pumping unit surface stroke frequency.',
    category: 'srp',
  },
  {
    id: 'PARAM_STROKE_LEN',
    name: 'Surface Stroke Length',
    unit: 'm',
    baselineValue: 2.5,
    minAllowed: 1.0,
    maxAllowed: 4.0,
    uncertaintyType: 'ABSOLUTE_RANGE',
    uncertaintyValue: 0.3, // ±0.3m
    sourceType: 'documented',
    sourceId: 'SRC_DGH_INDIA_02',
    isCalibrated: false,
    provenanceLabel: 'DOCUMENTED — Mechanical Unit Dimensions (DGH)',
    description: 'Polished rod travel distance per stroke.',
    category: 'srp',
  },
  {
    id: 'PARAM_PROD_COEFF',
    name: 'Productivity-Mobility Coefficient (C_prod)',
    unit: 'BOPD/(bar·D/cP)',
    baselineValue: 250.0, // Step 5.2 Calibrated value
    minAllowed: 10.0,
    maxAllowed: 350.0,
    uncertaintyType: 'PERCENTAGE',
    uncertaintyValue: 20.0, // ±20%
    sourceType: 'calibrated',
    sourceId: 'SRC_STEP_5_2_CALIBRATION',
    isCalibrated: true,
    provenanceLabel: 'CALIBRATED — Step 5.2 Fit (SPE 100642)',
    description: 'Productivity Index scaling factor calibrated against 2006 CSS pilot data.',
    category: 'production',
  },
];

export const DEFAULT_UNCERTAINTY_CONFIG: UncertaintyConfiguration = {
  sampleCount: DEFAULT_SAMPLE_COUNT,
  seed: DEFAULT_SEED,
  parameters: DEFAULT_UNCERTAINTY_PARAMETERS,
};
