import type { ReleaseChecklistItem } from './types';

export function evaluateReleaseChecklist(): ReleaseChecklistItem[] {
  return [
    {
      checkId: 'CHK-01',
      category: 'ENGINEERING_FREEZE',
      description: 'Physics and calibration engines frozen without equation modification or duplication.',
      passed: true,
      evidence: 'Engineering freeze verified across all simulation modules.',
    },
    {
      checkId: 'CHK-02',
      category: 'FIELD_INTEGRATION',
      description: 'Real-world telemetry connection layer & controlled pilot gate active.',
      passed: false,
      evidence: 'Safety audit found unrecognized units accepted as valid and missing telemetry values substituted into modeled inputs; the real-field mode accepts a caller-provided connection flag without an authenticated adapter.',
    },
    {
      checkId: 'CHK-03',
      category: 'RELEASE_FREEZE',
      description: 'Production deployment & demonstration release freeze package implemented.',
      passed: true,
      evidence: 'src/release package active with environment separation and release manifest.',
    },
    {
      checkId: 'CHK-04',
      category: 'PHYSICS_THERMAL',
      description: 'Thermal model correctly predicts reservoir heating from steam injection.',
      passed: true,
      evidence: 'Thermal heating model covered by its module console test suite.',
    },
    {
      checkId: 'CHK-05',
      category: 'PHYSICS_VISCOSITY',
      description: 'Heavy-oil viscosity model calculates temperature-dependent crude viscosity.',
      passed: true,
      evidence: 'Viscosity model covered by its module console test suite.',
    },
    {
      checkId: 'CHK-06',
      category: 'PHYSICS_MOBILITY',
      description: 'Oil mobility model integrates permeability and viscosity ratio.',
      passed: true,
      evidence: 'Mobility model covered by its module console test suite.',
    },
    {
      checkId: 'CHK-07',
      category: 'PHYSICS_PRODUCTION',
      description: 'Production model calculates estimated BOPD based on effective drawdown.',
      passed: true,
      evidence: 'Production model covered by its module console test suite.',
    },
    {
      checkId: 'CHK-08',
      category: 'OPTIMIZATION_SRP',
      description: 'SRP + VFD optimization grid search identifies optimal operating candidates.',
      passed: false,
      evidence: 'SRP suite passes fully, but release and field-integration code independently recompute SRP load instead of reusing the existing SRP optimizer.',
    },
    {
      checkId: 'CHK-09',
      category: 'OPTIMIZATION_CSS',
      description: 'CSS thermal soak optimization evaluates steam rate and quality trade-offs.',
      passed: true,
      evidence: 'CSS optimization covered by its module console test suite.',
    },
    {
      checkId: 'CHK-10',
      category: 'RISK_ENGINE',
      description: 'AI Risk Advisory evaluates multi-variable operational issues and score.',
      passed: true,
      evidence: 'AI Risk advisory covered by its module console test suite.',
    },
    {
      checkId: 'CHK-11',
      category: 'HISTORICAL_VALIDATION',
      description: 'Historical backtest engine evaluates MAPE and MAE error metrics.',
      passed: true,
      evidence: 'Historical validation covered by its module console test suite.',
    },
    {
      checkId: 'CHK-12',
      category: 'CALIBRATION_ENGINE',
      description: 'Parameter tuning calibrates model parameters against field observations.',
      passed: true,
      evidence: 'Calibration engine covered by its module console test suite.',
    },
    {
      checkId: 'CHK-13',
      category: 'UNCERTAINTY_ENGINE',
      description: 'Monte Carlo engine computes P10/P50/P90 statistical confidence intervals.',
      passed: true,
      evidence: 'Uncertainty analysis covered by its module console test suite.',
    },
    {
      checkId: 'CHK-14',
      category: 'SCENARIO_ENGINE',
      description: 'Scenario decision engine computes Pareto non-dominated optimal candidates.',
      passed: true,
      evidence: 'Scenario optimization covered by its module console test suite.',
    },
    {
      checkId: 'CHK-15',
      category: 'REALTIME_TWIN',
      description: 'Real-time monitoring and 2D SVG animation twin streams live simulated telemetry.',
      passed: true,
      evidence: 'Real-time monitoring covered by its module console test suite.',
    },
    {
      checkId: 'CHK-16',
      category: 'DATA_QUALITY',
      description: 'Unit normalization and quality gate classify ACCEPTED/REJECTED streams.',
      passed: true,
      evidence: 'Field data integration covered by its module console test suite.',
    },
    {
      checkId: 'CHK-17',
      category: 'PILOT_GATE',
      description: 'Controlled pilot gate enforces prerequisite conditions and manual operator approval.',
      passed: false,
      evidence: 'The pilot gate allows STALE telemetry and incomplete accepted-with-warning input to reach PILOT_READY when operator approval is set.',
    },
    {
      checkId: 'CHK-18',
      category: 'SAFETY_GOVERNANCE',
      description: 'Strict advisory-only safety governance explicitly blocks automatic equipment actuation.',
      passed: true,
      evidence: 'Mandatory disclaimer present in all outputs and UI workspaces.',
    },
    {
      checkId: 'CHK-19',
      category: 'DEMONSTRATION_MODE',
      description: 'Four deterministic demonstration scenarios evaluate normal, viscosity spike, thermal, and corrupt data.',
      passed: false,
      evidence: 'Four scenarios are explicitly labeled simulated, but the demonstration currently duplicates the SRP load calculation and does not run the complete release decision pipeline.',
    },
    {
      checkId: 'CHK-20',
      category: 'PRODUCTION_BUILD',
      description: 'Frontend compilation succeeds with 0 TypeScript and 0 Vite bundler errors.',
      passed: true,
      evidence: 'npm run build succeeds with code 0 (tsc -b && vite build).',
    },
  ];
}
