import type { ReleaseChecklistItem } from './types';

export function evaluateReleaseChecklist(): ReleaseChecklistItem[] {
  return [
    {
      checkId: 'CHK-01',
      category: 'ENGINEERING_FREEZE',
      description: 'Step 5 physics and calibration engines frozen without equation modification or duplication.',
      passed: true,
      evidence: 'Step 5 engineering freeze verified across Steps 5.1 through 5.13.',
    },
    {
      checkId: 'CHK-02',
      category: 'FIELD_INTEGRATION',
      description: 'Step 6.1 real-world telemetry connection layer & controlled pilot gate active.',
      passed: false,
      evidence: 'Safety audit found unrecognized units accepted as valid and missing telemetry values substituted into modeled inputs; the real-field mode accepts a caller-provided connection flag without an authenticated adapter.',
    },
    {
      checkId: 'CHK-03',
      category: 'RELEASE_FREEZE',
      description: 'Step 6.2 production deployment & demonstration release freeze package implemented.',
      passed: true,
      evidence: 'src/release package active with environment separation and release manifest.',
    },
    {
      checkId: 'CHK-04',
      category: 'PHYSICS_THERMAL',
      description: 'Step 4.3 thermal model correctly predicts reservoir heating from steam injection.',
      passed: true,
      evidence: 'Verified 8/8 thermal model unit tests passing.',
    },
    {
      checkId: 'CHK-05',
      category: 'PHYSICS_VISCOSITY',
      description: 'Step 4.4 heavy-oil viscosity model calculates temperature-dependent crude viscosity.',
      passed: true,
      evidence: 'Verified 7/7 viscosity model unit tests passing.',
    },
    {
      checkId: 'CHK-06',
      category: 'PHYSICS_MOBILITY',
      description: 'Step 4.5 oil mobility model integrates permeability and viscosity ratio.',
      passed: true,
      evidence: 'Verified 12/12 mobility model unit tests passing.',
    },
    {
      checkId: 'CHK-07',
      category: 'PHYSICS_PRODUCTION',
      description: 'Step 4.6 production model calculates estimated BOPD based on effective drawdown.',
      passed: true,
      evidence: 'Verified 14/14 production model unit tests passing.',
    },
    {
      checkId: 'CHK-08',
      category: 'OPTIMIZATION_SRP',
      description: 'Step 4.7 SRP + VFD optimization grid search identifies optimal operating candidates.',
      passed: false,
      evidence: 'SRP suite passes 15/15, but release and field-integration code independently recompute SRP load instead of reusing the existing SRP optimizer.',
    },
    {
      checkId: 'CHK-09',
      category: 'OPTIMIZATION_CSS',
      description: 'Step 4.8 CSS thermal soak optimization evaluates steam rate and quality trade-offs.',
      passed: true,
      evidence: 'Verified 22/22 CSS optimization unit tests passing.',
    },
    {
      checkId: 'CHK-10',
      category: 'RISK_ENGINE',
      description: 'Step 4.9 AI Risk Advisory evaluates multi-variable operational issues and score.',
      passed: true,
      evidence: 'Verified 10/10 AI Risk unit tests passing.',
    },
    {
      checkId: 'CHK-11',
      category: 'HISTORICAL_VALIDATION',
      description: 'Step 5.1 historical backtest engine evaluates MAPE and MAE error metrics.',
      passed: true,
      evidence: 'Verified 14/14 historical validation unit tests passing.',
    },
    {
      checkId: 'CHK-12',
      category: 'CALIBRATION_ENGINE',
      description: 'Step 5.2 parameter tuning calibrates model parameters against field observations.',
      passed: true,
      evidence: 'Verified 16/16 historical calibration unit tests passing.',
    },
    {
      checkId: 'CHK-13',
      category: 'UNCERTAINTY_ENGINE',
      description: 'Step 5.3 Monte Carlo engine computes P10/P50/P90 statistical confidence intervals.',
      passed: true,
      evidence: 'Verified 24/24 uncertainty analysis unit tests passing.',
    },
    {
      checkId: 'CHK-14',
      category: 'SCENARIO_ENGINE',
      description: 'Step 5.4 scenario decision engine computes Pareto non-dominated optimal candidates.',
      passed: true,
      evidence: 'Verified 20/20 scenario optimization unit tests passing.',
    },
    {
      checkId: 'CHK-15',
      category: 'REALTIME_TWIN',
      description: 'Step 5.5 real-time monitoring and 2D SVG animation twin streams live simulated telemetry.',
      passed: true,
      evidence: 'Verified 30/30 real-time monitoring unit tests passing.',
    },
    {
      checkId: 'CHK-16',
      category: 'DATA_QUALITY',
      description: 'Step 5.6/6.1 unit normalization and quality gate classify ACCEPTED/REJECTED streams.',
      passed: true,
      evidence: 'Verified 30/30 field data integration unit tests passing.',
    },
    {
      checkId: 'CHK-17',
      category: 'PILOT_GATE',
      description: 'Controlled pilot gate enforces prerequisite conditions and manual operator approval.',
      passed: false,
      evidence: 'The pilot gate allows STALE telemetry and incomplete accepted-with-warning input to reach PILOT_READY when operator approval is set.',
    },
    {
      checkId: 'CHK-18',
      category: 'SAFETY_GOVERNANCE',
      description: 'Strict advisory-only safety governance explicitly blocks automatic equipment actuation.',
      passed: true,
      evidence: 'Mandatory disclaimer present in all outputs and UI workspaces.',
    },
    {
      checkId: 'CHK-19',
      category: 'DEMONSTRATION_MODE',
      description: 'Four deterministic demonstration scenarios evaluate normal, viscosity spike, thermal, and corrupt data.',
      passed: false,
      evidence: 'Four scenarios are explicitly labeled simulated, but the demonstration currently duplicates the SRP load calculation and does not run the complete release decision pipeline.',
    },
    {
      checkId: 'CHK-20',
      category: 'PRODUCTION_BUILD',
      description: 'Frontend compilation succeeds with 0 TypeScript and 0 Vite bundler errors.',
      passed: true,
      evidence: 'npm run build succeeds with code 0 (tsc -b && vite build).',
    },
  ];
}
