import type { HistoricalObservation, BacktestCase } from './types';
import type { ScenarioInputValues } from '../scenario/types';
import { BASELINE_INPUT_VALUES } from '../scenario/defaults';

/**
 * Historical observation dataset for Baghewala Heavy-Oil Field.
 * NOTE: All records in this dataset represent reference demonstration/synthetic baselines.
 * Explicitly marked as DEMONSTRATION_DATA / SYNTHETIC_DATA to comply with engineering data governance.
 */
export const BAGHEWALA_HISTORICAL_DATASET: HistoricalObservation[] = [
  {
    id: 'HIST-001',
    name: 'Baghewala Native Appraisal Baseline (1995)',
    date: '1995-04-15',
    dateOrYear: '1995',
    wellId: 'BGW-REP-01',
    parameter: 'Native Crude Oil Viscosity & Production',
    observedValue: 0.75,
    unit: 'BOPD',
    sourceId: 'SRC_SPE_CSS_03',
    sourceType: 'publication',
    confidence: 'HIGH',
    reservoirTemperatureC: 48.0,
    reservoirPressureBar: 48.0,
    steamInjectionRateTpd: 0.0,
    steamQualityPercent: 0.0,
    waterCutPercent: 20.0,
    spm: 8.0,
    strokeLengthMeters: 2.5,
    permeabilityDarcy: 2.5,
    observedProductionBopd: 0.75,
    observedViscosityCp: 15000.0,
    observedTemperatureC: 48.0,
    source: 'DEMONSTRATION_DATA',
    notes: 'Native appraisal baseline prior to thermal stimulation.',
  },
  {
    id: 'HIST-002',
    name: 'Pilot Cyclic Steam Stimulation Trial (2006)',
    date: '2006-02-10',
    dateOrYear: '2006',
    wellId: 'BGW-CSS-01',
    parameter: 'CSS Peak Thermal Production',
    observedValue: 4.85,
    unit: 'BOPD',
    sourceId: 'SRC_SPE_CSS_03',
    sourceType: 'publication',
    confidence: 'HIGH',
    reservoirTemperatureC: 75.0,
    reservoirPressureBar: 45.0,
    steamInjectionRateTpd: 120.0,
    steamQualityPercent: 80.0,
    waterCutPercent: 25.0,
    spm: 10.0,
    strokeLengthMeters: 2.8,
    permeabilityDarcy: 2.5,
    observedProductionBopd: 4.85,
    observedViscosityCp: 780.0,
    observedTemperatureC: 75.0,
    source: 'DEMONSTRATION_DATA',
    notes: 'Pilot CSS Cycle 1 peak thermal production response.',
  },
  {
    id: 'HIST-003',
    name: 'Late Soak Response Case (2008)',
    date: '2008-08-20',
    dateOrYear: '2008',
    wellId: 'BGW-CSS-01',
    parameter: 'Late Soak Production Rate',
    observedValue: 2.65,
    unit: 'BOPD',
    sourceId: 'SRC_OIL_PUB_01',
    sourceType: 'report',
    confidence: 'MEDIUM',
    reservoirTemperatureC: 62.0,
    reservoirPressureBar: 42.0,
    steamInjectionRateTpd: 80.0,
    steamQualityPercent: 75.0,
    waterCutPercent: 35.0,
    spm: 9.0,
    strokeLengthMeters: 2.5,
    permeabilityDarcy: 2.5,
    observedProductionBopd: 2.65,
    observedViscosityCp: 3200.0,
    observedTemperatureC: 62.0,
    source: 'DEMONSTRATION_DATA',
    notes: 'Late soak phase response with moderate thermal drawdown.',
  },
  {
    id: 'HIST-004',
    name: 'Viscosity Stagnation Trial (2012)',
    date: '2012-11-05',
    dateOrYear: '2012',
    wellId: 'BGW-STAG-02',
    parameter: 'Stagnant Formation Production',
    observedValue: 0.35,
    unit: 'BOPD',
    sourceId: 'SRC_SYNTHETIC',
    sourceType: 'reference',
    confidence: 'MEDIUM',
    reservoirTemperatureC: 35.0,
    reservoirPressureBar: 38.0,
    steamInjectionRateTpd: 0.0,
    steamQualityPercent: 0.0,
    waterCutPercent: 40.0,
    spm: 6.0,
    strokeLengthMeters: 2.0,
    permeabilityDarcy: 1.8,
    observedProductionBopd: 0.35,
    observedViscosityCp: 42000.0,
    observedTemperatureC: 35.0,
    source: 'SYNTHETIC_DATA',
    notes: 'Cold formation viscosity stagnation test case.',
  },
  {
    id: 'HIST-005',
    name: 'Thermal Intensive Soak Trial (2015)',
    date: '2015-03-30',
    dateOrYear: '2015',
    wellId: 'BGW-BOOST-03',
    parameter: 'Intensive Thermal Production Rate',
    observedValue: 8.20,
    unit: 'BOPD',
    sourceId: 'SRC_SYNTHETIC',
    sourceType: 'reference',
    confidence: 'HIGH',
    reservoirTemperatureC: 85.0,
    reservoirPressureBar: 46.0,
    steamInjectionRateTpd: 150.0,
    steamQualityPercent: 85.0,
    waterCutPercent: 20.0,
    spm: 12.0,
    strokeLengthMeters: 3.2,
    permeabilityDarcy: 3.0,
    observedProductionBopd: 8.20,
    observedViscosityCp: 320.0,
    observedTemperatureC: 85.0,
    source: 'SYNTHETIC_DATA',
    notes: 'High steam rate intensive soak trial.',
  },
  {
    id: 'HIST-006',
    name: 'Depleted Reservoir Pressure Trial (2019)',
    date: '2019-09-12',
    dateOrYear: '2019',
    wellId: 'BGW-DEPL-01',
    parameter: 'Depleted Production Rate',
    observedValue: 1.25,
    unit: 'BOPD',
    sourceId: 'SRC_OIL_PUB_01',
    sourceType: 'report',
    confidence: 'MEDIUM',
    reservoirTemperatureC: 52.0,
    reservoirPressureBar: 30.0,
    steamInjectionRateTpd: 60.0,
    steamQualityPercent: 70.0,
    waterCutPercent: 55.0,
    spm: 8.0,
    strokeLengthMeters: 2.5,
    permeabilityDarcy: 2.2,
    observedProductionBopd: 1.25,
    observedViscosityCp: 7500.0,
    observedTemperatureC: 52.0,
    source: 'DEMONSTRATION_DATA',
    notes: 'Depleted reservoir pressure drawdown trial case.',
  },
];

export function historicalObservationToInputs(obs: HistoricalObservation): ScenarioInputValues {
  return {
    ...BASELINE_INPUT_VALUES,
    reservoirTemperatureC: obs.reservoirTemperatureC,
    reservoirPressureBar: obs.reservoirPressureBar,
    steamInjectionRateTpd: obs.steamInjectionRateTpd,
    steamQualityPercent: obs.steamQualityPercent,
    waterCutPercent: obs.waterCutPercent,
    spm: obs.spm,
    strokeLengthMeters: obs.strokeLengthMeters,
    permeabilityDarcy: obs.permeabilityDarcy,
  };
}

export function loadHistoricalBacktestDataset(): BacktestCase[] {
  return BAGHEWALA_HISTORICAL_DATASET.map((obs) => ({
    id: `CASE_${obs.id}`,
    name: obs.name ?? `Historical Case ${obs.id}`,
    description: obs.notes ?? 'Documented historical operating case.',
    yearOrDate: String(obs.dateOrYear ?? obs.date),
    availability: 'PARTIAL',
    inputs: historicalObservationToInputs(obs),
    observations: [obs],
  }));
}
