import {
  JODHPUR_RESERVOIR_PROFILE,
  BAGHEWALA_CRUDE_PROFILE,
  HISTORICAL_CSS_CYCLES,
  HISTORICAL_PRODUCTION_SNAPSHOTS,
} from '../../data/baghewala';
import type { BacktestCase } from './types';

export function loadHistoricalBacktestDataset(): BacktestCase[] {
  const css1 = HISTORICAL_CSS_CYCLES[0];
  const prodSnap1 = HISTORICAL_PRODUCTION_SNAPSHOTS[0];

  return [
    {
      id: 'CASE_NATIVE_1995',
      name: 'Baghewala Native Appraisal State (1995)',
      description: 'Documented native reservoir conditions prior to thermal steam stimulation.',
      yearOrDate: '1995',
      availability: 'PARTIAL',
      inputs: {
        ambientTemperatureC: 35.0,
        reservoirTemperatureC: JODHPUR_RESERVOIR_PROFILE.reservoirTemperatureC.value ?? 48.0,
        steamInjectionRateTpd: 0.0,
        steamQualityPercent: 0.0,
        soakDurationDays: 0.0,
        vfdFrequencyHz: 50.0,
        spm: 8.0,
        strokeLengthMeters: 2.5,
      },
      observations: [
        {
          id: 'OBS_NATIVE_TEMP',
          dateOrYear: 1995,
          parameter: 'Initial Reservoir Temperature',
          observedValue: JODHPUR_RESERVOIR_PROFILE.reservoirTemperatureC.value,
          unit: '°C',
          sourceId: JODHPUR_RESERVOIR_PROFILE.reservoirTemperatureC.sourceId ?? 'SRC_SPE_CSS_03',
          sourceType: JODHPUR_RESERVOIR_PROFILE.reservoirTemperatureC.sourceType,
          confidence: 'HIGH',
          notes: 'Native static reservoir temperature prior to steam injection.',
        },
        {
          id: 'OBS_NATIVE_VISC',
          dateOrYear: 1995,
          parameter: 'Native Crude Oil Viscosity @ 48°C',
          observedValue: BAGHEWALA_CRUDE_PROFILE.viscosityDataPoints[1].viscosityCp,
          unit: 'cP',
          sourceId: BAGHEWALA_CRUDE_PROFILE.viscosityDataPoints[1].sourceId ?? 'SRC_SPE_CSS_03',
          sourceType: BAGHEWALA_CRUDE_PROFILE.viscosityDataPoints[1].sourceType,
          confidence: 'HIGH',
          notes: 'Documented viscosity at 48°C reservoir temperature.',
        },
        {
          id: 'OBS_NATIVE_PERM',
          dateOrYear: 1995,
          parameter: 'Reservoir Permeability',
          observedValue: JODHPUR_RESERVOIR_PROFILE.permeabilityDarcies.value,
          unit: 'D',
          sourceId: JODHPUR_RESERVOIR_PROFILE.permeabilityDarcies.sourceId ?? 'SRC_OIL_PUB_01',
          sourceType: JODHPUR_RESERVOIR_PROFILE.permeabilityDarcies.sourceType,
          confidence: 'HIGH',
          notes: 'Pay sandstone permeability from core data.',
        },
        {
          id: 'OBS_NATIVE_PRESSURE',
          dateOrYear: 1995,
          parameter: 'Initial Reservoir Pressure',
          observedValue: JODHPUR_RESERVOIR_PROFILE.initialPressureBar.value,
          unit: 'bar',
          sourceId: JODHPUR_RESERVOIR_PROFILE.initialPressureBar.sourceId ?? 'SRC_SPE_CSS_03',
          sourceType: JODHPUR_RESERVOIR_PROFILE.initialPressureBar.sourceType,
          confidence: 'MEDIUM',
          notes: 'Hydrostatic pressure estimation for 1100m depth.',
        },
      ],
    },
    {
      id: 'CASE_CSS_PILOT_2006',
      name: 'Pilot Cyclic Steam Stimulation Trial (2006)',
      description: 'Documented pilot huff-and-puff steam injection trial Cycle 1.',
      yearOrDate: '2006',
      availability: 'PARTIAL',
      inputs: {
        ambientTemperatureC: 35.0,
        reservoirTemperatureC: 48.0,
        steamInjectionRateTpd: 80.0,
        steamQualityPercent: 75.0,
        soakDurationDays: css1?.soakDurationDays?.value ?? 7.0,
        vfdFrequencyHz: 50.0,
        spm: 8.0,
        strokeLengthMeters: 2.5,
      },
      observations: [
        {
          id: 'OBS_CSS_STEAM_VOL',
          dateOrYear: 2006,
          parameter: 'Steam Volume Injected',
          observedValue: css1?.steamVolumeTons?.value ?? 1500,
          unit: 'tons',
          sourceId: css1?.steamVolumeTons?.sourceId ?? 'SRC_SPE_CSS_03',
          sourceType: css1?.steamVolumeTons?.sourceType ?? 'documented',
          confidence: 'HIGH',
          notes: 'Documented pilot steam injection volume for Cycle 1.',
        },
        {
          id: 'OBS_CSS_SOAK_DAYS',
          dateOrYear: 2006,
          parameter: 'Soak Phase Duration',
          observedValue: css1?.soakDurationDays?.value ?? 7,
          unit: 'days',
          sourceId: css1?.soakDurationDays?.sourceId ?? 'SRC_SPE_CSS_03',
          sourceType: css1?.soakDurationDays?.sourceType ?? 'documented',
          confidence: 'HIGH',
          notes: 'Shut-in soak duration prior to reopening for production.',
        },
        {
          id: 'OBS_CSS_PEAK_PROD',
          dateOrYear: 2006,
          parameter: 'Peak Oil Production Rate Snapshot',
          observedValue: prodSnap1?.oilProductionBpd?.value ?? 120,
          unit: 'BOPD',
          sourceId: prodSnap1?.oilProductionBpd?.sourceId ?? 'SRC_SPE_CSS_03',
          sourceType: prodSnap1?.oilProductionBpd?.sourceType ?? 'documented',
          confidence: 'HIGH',
          notes: 'Peak post-soak oil production rate during early CSS cycle 1.',
        },
        {
          id: 'OBS_CSS_CUM_OIL',
          dateOrYear: 2006,
          parameter: 'Cumulative Oil Recovered',
          observedValue: css1?.oilRecoveredTons?.value ?? 1850,
          unit: 'tons',
          sourceId: css1?.oilRecoveredTons?.sourceId ?? 'SRC_SPE_CSS_03',
          sourceType: css1?.oilRecoveredTons?.sourceType ?? 'documented',
          confidence: 'HIGH',
          notes: 'Total oil produced during Cycle 1.',
        },
        {
          id: 'OBS_CSS_RESERVOIR_TEMP_PEAK',
          dateOrYear: 2006,
          parameter: 'Downhole Thermal Temperature Profile',
          observedValue: null,
          unit: '°C',
          sourceId: 'SRC_SPE_CSS_03',
          sourceType: 'documented',
          confidence: 'LOW',
          notes: 'INSUFFICIENT HISTORICAL DATA: Continuous downhole temperature log unavailable in published literature.',
        },
      ],
    },
    {
      id: 'CASE_SRP_VFD_2012',
      name: 'SRP & VFD Artificial Lift Integration (2012)',
      description: 'Evaluation of Sucker Rod Pumping with Variable Frequency Drive.',
      yearOrDate: '2012',
      availability: 'PARTIAL',
      inputs: {
        ambientTemperatureC: 35.0,
        reservoirTemperatureC: 48.0,
        steamInjectionRateTpd: 50.0,
        steamQualityPercent: 75.0,
        soakDurationDays: 7.0,
        vfdFrequencyHz: 50.0,
        spm: 8.0,
        strokeLengthMeters: 2.5,
      },
      observations: [
        {
          id: 'OBS_SRP_VFD_HZ',
          dateOrYear: 2012,
          parameter: 'VFD Operating Frequency',
          observedValue: 50.0,
          unit: 'Hz',
          sourceId: 'SRC_DGH_INDIA_02',
          sourceType: 'documented',
          confidence: 'HIGH',
          notes: 'Documented baseline VFD operational frequency.',
        },
        {
          id: 'OBS_SRP_SPM',
          dateOrYear: 2012,
          parameter: 'Surface Pumping Speed',
          observedValue: 8.0,
          unit: 'SPM',
          sourceId: 'SRC_DGH_INDIA_02',
          sourceType: 'documented',
          confidence: 'HIGH',
          notes: 'Standard surface stroke rate.',
        },
        {
          id: 'OBS_SRP_STROKE',
          dateOrYear: 2012,
          parameter: 'Surface Stroke Length',
          observedValue: 2.5,
          unit: 'm',
          sourceId: 'SRC_DGH_INDIA_02',
          sourceType: 'documented',
          confidence: 'HIGH',
          notes: 'Standard polished rod stroke length.',
        },
        {
          id: 'OBS_SRP_LOAD_CARD',
          dateOrYear: 2012,
          parameter: 'Downhole Dynamometer Rod Load',
          observedValue: null,
          unit: 'kN',
          sourceId: 'SRC_DGH_INDIA_02',
          sourceType: 'documented',
          confidence: 'LOW',
          notes: 'INSUFFICIENT HISTORICAL DATA: Measured dynamometer load card values unavailable in public records.',
        },
      ],
    },
    {
      id: 'CASE_BASELINE_2026',
      name: 'Digital Twin Reference Baseline (2026)',
      description: 'Antigravity Digital Twin reference baseline operational state.',
      yearOrDate: '2026',
      availability: 'COMPLETE',
      inputs: {
        ambientTemperatureC: 35.0,
        reservoirTemperatureC: 48.0,
        steamInjectionRateTpd: 50.0,
        steamQualityPercent: 75.0,
        soakDurationDays: 7.0,
        vfdFrequencyHz: 50.0,
        spm: 8.0,
        strokeLengthMeters: 2.5,
      },
      observations: [
        {
          id: 'OBS_REF_TEMP',
          dateOrYear: 2026,
          parameter: 'Baseline Reservoir Temperature',
          observedValue: 48.0,
          unit: '°C',
          sourceId: 'SRC_SPE_CSS_03',
          sourceType: 'documented',
          confidence: 'HIGH',
          notes: 'Baghewala reference temperature.',
        },
        {
          id: 'OBS_REF_VISC',
          dateOrYear: 2026,
          parameter: 'Baseline Oil Viscosity @ 48°C',
          observedValue: 15000,
          unit: 'cP',
          sourceId: 'SRC_SPE_CSS_03',
          sourceType: 'documented',
          confidence: 'HIGH',
          notes: 'Baghewala reference viscosity.',
        },
        {
          id: 'OBS_REF_DRAWDOWN',
          dateOrYear: 2026,
          parameter: 'Effective Operating Drawdown',
          observedValue: 30.0,
          unit: 'bar',
          sourceId: 'SRC_ESTIMATION_04',
          sourceType: 'derived',
          confidence: 'MEDIUM',
          notes: 'Derived reference drawdown pressure differential.',
        },
      ],
    },
  ];
}
