import { useMemo, useState } from "react";
import { Link } from "react-router-dom";
import {
  Activity, AlertTriangle, Bell, Boxes, CalendarDays, CheckCircle2, ChevronDown,
  CircleAlert, Database, Droplet, FileText, Flame, Gauge, GitBranch, PanelLeftClose,
  Radio, RefreshCw, Search, Settings, ShieldCheck, SlidersHorizontal, Sparkles,
  Thermometer, Upload, Waves, Zap,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import twinImg from "@/assets/digital-twin.jpg";
import { useDocumentTitle } from "@/hooks/useDocumentTitle";

const navItems = [
  { icon: Gauge, label: "Dashboard", to: "/" as const },  { icon: Boxes, label: "Digital Twin", to: "/digital-twin" as const },
  { icon: Activity, label: "Well Dynamics", to: "/well-dynamics" as const },  { icon: SlidersHorizontal, label: "Simulation", to: "/simulation" as const },
  { icon: Waves, label: "Optimization", to: "/optimization" as const }, { icon: Radio, label: "Live Monitoring", to: "/monitoring" as const },
  { icon: FileText, label: "Reports", to: "/reports" as const },
];
function Sidebar() {
  return <aside className="fixed inset-y-0 left-0 z-40 hidden w-[196px] flex-col bg-sidebar text-sidebar-foreground lg:flex">
    <div className="flex items-center gap-2 px-4 pb-4 pt-3"><span className="flex h-9 w-9 items-center justify-center rounded-md bg-sidebar-primary text-sidebar-primary-foreground"><Flame className="h-6 w-6" fill="currentColor" /></span><div><p className="text-sm font-bold text-sidebar-accent-foreground">BAGHEWALA</p><p className="text-[9px] text-sidebar-foreground/60">HEAVY-OIL ASSET</p></div><PanelLeftClose className="ml-auto h-4 w-4 text-sidebar-foreground/50" /></div>
    <nav className="space-y-0.5 px-2">{navItems.map(item => <Link key={item.label} to={item.to} className="flex items-center gap-3 rounded-md px-3 py-2 text-xs text-sidebar-foreground/85 hover:bg-sidebar-accent"><item.icon className="h-4 w-4" />{item.label}{item.label === "Reports" && <span className="ml-auto">›</span>}</Link>)}
      <p className="border-t border-sidebar-border px-3 pb-1 pt-3 text-[9px] tracking-wider text-sidebar-foreground/45">TOOLS</p>
      <Link to="/data-explorer" className="flex items-center gap-3 rounded-md bg-sidebar-primary px-3 py-2 text-xs font-semibold text-sidebar-primary-foreground"><Database className="h-4 w-4" />Data Explorer</Link>
      <div className="flex items-center gap-3 px-3 py-2 text-xs"><GitBranch className="h-4 w-4" />Scenarios</div>
    </nav>
    <div className="mx-3 mb-3 mt-auto overflow-hidden rounded-md border border-sidebar-border bg-sidebar-accent/35"><img src={twinImg} alt="Field digital twin geological model" className="h-20 w-full object-cover" /><div className="p-3"><p className="text-xs font-semibold text-sidebar-accent-foreground">Field Digital Twin</p><p className="mt-1 text-[9px] leading-relaxed text-sidebar-foreground/65">Integrated simulation &amp; real-time data for better decisions.</p></div></div>
  </aside>;
}
function Topbar() {
  return <header className="flex h-11 items-center border-b border-border bg-card px-5"><PanelLeftClose className="mr-5 h-4 w-4 rotate-180 text-muted-foreground" /><div className="flex w-[405px] items-center gap-2 rounded-md border border-input bg-background px-3 py-1.5"><Search className="h-3.5 w-3.5 text-muted-foreground" /><input aria-label="Search" placeholder="Search wells, scenarios, or parameters..." className="min-w-0 flex-1 bg-transparent text-[9px] outline-none" /><kbd className="rounded border border-border px-1 text-[8px] text-muted-foreground">Ctrl + K</kbd></div><div className="ml-auto flex items-center gap-3"><Button size="icon" variant="ghost" className="h-8 w-8" aria-label="Notifications"><Bell /></Button><Button size="icon" variant="ghost" className="h-8 w-8" aria-label="Settings"><Settings /></Button><span className="flex h-8 w-8 items-center justify-center rounded-full bg-foreground text-xs font-bold text-background">OI</span><div><p className="text-[10px] font-bold">Oil India Limited</p><p className="text-[8px] text-muted-foreground">Administrator</p></div><ChevronDown className="h-3.5 w-3.5" /></div></header>;
}
const sampleRows = [
  ["#1", "2026-09-30T01:10:00Z", "BG-01", "HISTORICAL", "PARTIALLY_VALID", "63", "45", "6", "3", "150", "100"],
  ["#2", "2026-09-30T01:12:00Z", "BG-01", "HISTORICAL", "PARTIALLY_VALID", "68", "48", "6.5", "3.2", "150", "112"],
  ["#3", "2026-09-30T01:14:00Z", "BG-01", "HISTORICAL", "PARTIALLY_VALID", "64", "50", "7", "3.2", "150", "118"],
  ["#4", "2026-09-30T01:16:00Z", "BG-01", "HISTORICAL", "PARTIALLY_VALID", "75", "55", "7", "3.2", "150", "126"],
  ["#5", "2026-09-30T01:18:00Z", "BG-01", "HISTORICAL", "PARTIALLY_VALID", "80", "52", "7.3", "3.5", "150", "146"],
];
const payloads = sampleRows.map((r) => ({ timestamp: r[1], wellId: r[2], reservoirTemperature: Number(r[5]), reservoirPressure: Number(r[11]), measuredTemperature: `${r[5]} °C`, measuredPressure: `${r[11]} bar`, dataQuality: 0.98 }));
function AuditMetric({ icon: Icon, label, value, tone }: { icon: typeof Gauge; label: string; value: string; tone: string }) {
  return <div className="flex h-10 items-center gap-2 rounded-md border border-border bg-background px-2"><span className={`flex h-7 w-7 items-center justify-center rounded-full ${tone}`}><Icon className="h-3.5 w-3.5" /></span><div><p className="text-[6px] uppercase text-muted-foreground">{label}</p><p className="text-[11px] font-bold">{value}</p></div></div>;
}
export function DataExplorerPage() {
  useDocumentTitle({ title: "Data Explorer — Baghewala Heavy-Oil Asset", description: "Inspect, normalize, validate, and audit Baghewala field and telemetry data before monitoring." });
  const [source, setSource] = useState("historical");
  const [policy, setPolicy] = useState("linear");
  const [rejectOutliers, setRejectOutliers] = useState(false);
  const [record, setRecord] = useState(0);
  const [imported, setImported] = useState(false);
  const current = payloads[record] ?? payloads[0];
  const raw = useMemo(() => JSON.stringify(current, null, 2), [current]);
  if (!current) return null;
  return <div className="min-h-screen bg-background"><Sidebar /><div className="lg:pl-[196px]"><div className="min-w-[1080px]"><Topbar /><main className="space-y-2 px-4 pb-4 pt-2">
    <section className="flex items-center border-l-4 border-primary pl-3"><div><div className="flex items-center gap-3"><h1 className="text-[24px] font-bold leading-none">Data Explorer</h1><span className="rounded border border-border px-2 py-1 text-[7px] font-bold tracking-wider text-muted-foreground">DATA INSPECTION</span></div><p className="mt-1 text-[8px] text-muted-foreground">Inspect, normalize and validate imported data. Historical and simulated telemetry before it reaches the live monitoring view.</p></div><div className="ml-auto flex gap-2"><span className="rounded border border-sky-foreground/20 bg-sky-soft px-3 py-1 text-[7px] font-bold text-sky-foreground">◈ SOURCE　 HISTORICAL_APPRAISAL_DATA</span><span className="rounded border border-violet-foreground/20 bg-violet-soft px-3 py-1 text-[7px] font-bold text-violet-foreground">◉ SCORE　 90/100</span></div></section>
    <section className="flex items-center rounded-md border border-primary bg-amber-soft/35 px-3 py-2"><AlertTriangle className="mr-3 h-4 w-4 text-primary" /><div><p className="text-[8px] font-bold text-accent-foreground">BAGHEWALA FIELD INGESTION &amp; PROVENANCE POLICY</p><p className="mt-0.5 text-[6px] text-muted-foreground">Data ingestion &amp; provenance notice: Ingested field and telemetry data pass through unit normalization, schema validation, quality scoring, and outlier detection before state estimation. Values are <b>MEASURED</b>, <b>SIMULATED</b>, or <b>UNIT_UNKNOWN</b>.</p></div><ChevronDown className="ml-auto h-3 w-3" /></section>
    <section className="grid grid-cols-[.58fr_1fr] gap-3"><div className="rounded-md border border-border bg-card p-2 shadow-sm"><h2 className="mb-2 flex items-center gap-2 text-[9px] font-bold"><Database className="h-4 w-4 text-mint-foreground" />Ingestion Parameters</h2><label className="block text-[7px] font-semibold">Data Source Type</label><Select value={source} onValueChange={setSource}><SelectTrigger aria-label="Data Source Type" className="mt-0.5 h-6 text-[7px]"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="historical">HISTORICAL_APPRAISAL_DATA</SelectItem><SelectItem value="telemetry">LIVE_TELEMETRY</SelectItem><SelectItem value="simulation">SIMULATED_DATA</SelectItem></SelectContent></Select><label className="mt-1 block text-[7px] font-semibold">Missing Value Policy</label><Select value={policy} onValueChange={setPolicy}><SelectTrigger aria-label="Missing Value Policy" className="mt-0.5 h-6 text-[7px]"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="linear">LINEAR_INTERPOLATION (PREFERRED)</SelectItem><SelectItem value="forward">FORWARD_FILL</SelectItem><SelectItem value="reject">REJECT_INCOMPLETE</SelectItem></SelectContent></Select><label className="mt-2 flex items-center gap-2 text-[7px]"><Checkbox checked={rejectOutliers} onCheckedChange={(v) => setRejectOutliers(v === true)} />Reject Extreme Outliers Automatically</label><div className="mt-2 grid grid-cols-[1fr_100px] gap-2"><Button className="h-7 bg-mint-foreground text-[8px] text-primary-foreground" onClick={() => setImported(true)}><Upload />{imported ? "Payload Imported" : "Import Payload"}</Button><Button variant="outline" className="h-7 text-[8px]" onClick={() => { setSource("historical"); setPolicy("linear"); setRejectOutliers(false); setImported(false); }}>Reset Sample</Button></div></div>
      <div className="rounded-md border border-border bg-card p-2 shadow-sm"><div className="flex items-center"><h2 className="flex items-center gap-2 text-[9px] font-bold"><GitBranch className="h-4 w-4 text-sky-foreground" />Raw Dataset Payload (JSON / CSV Format)</h2><span className="ml-auto text-[7px] text-muted-foreground">Max 1e5, 5,000 records</span></div><pre className="mt-2 h-[88px] overflow-auto rounded-md border border-sky-foreground/25 bg-sky-soft/20 p-2 text-[7px] leading-[1.25] text-mint-foreground">{raw}</pre></div></section>
    <section className="rounded-md border border-border bg-card p-2 shadow-sm"><div className="flex items-center"><h2 className="flex items-center gap-2 text-[9px] font-bold"><ShieldCheck className="h-4 w-4 text-violet-foreground" />Data Quality Audit Report</h2><span className="ml-auto rounded border border-mint-foreground/30 bg-mint px-2 py-1 text-[7px] font-bold text-mint-foreground">STATUS: VALID</span></div><div className="mt-2 grid grid-cols-7 gap-2"><AuditMetric icon={ShieldCheck} label="Overall quality score" value="90/100" tone="bg-violet-soft text-violet-foreground" /><AuditMetric icon={Database} label="Total records" value="5" tone="bg-mint text-mint-foreground" /><AuditMetric icon={CheckCircle2} label="Valid records" value="5" tone="bg-mint text-mint-foreground" /><AuditMetric icon={CircleAlert} label="Invalid records" value="0" tone="bg-rose-soft text-rose-foreground" /><AuditMetric icon={Gauge} label="Completeness" value="66.7%" tone="bg-sky-soft text-sky-foreground" /><AuditMetric icon={AlertTriangle} label="Outliers detected" value={rejectOutliers ? "5" : "0"} tone="bg-amber-soft text-accent-foreground" /><AuditMetric icon={Sparkles} label="Suspected values" value="26" tone="bg-violet-soft text-violet-foreground" /></div></section>
    <section className="rounded-md border border-primary bg-amber-soft/25 px-3 py-2"><div className="flex"><AlertTriangle className="mr-3 h-4 w-4 text-primary" /><div><p className="text-[8px] font-bold text-accent-foreground">Quality Audit Warnings</p><ul className="mt-1 list-disc pl-4 text-[6px] leading-[1.3]"><li>Unit metadata absent for category ‘temperature’. Value marked as UNIT_UNKNOWN.</li><li>Unit metadata absent for category ‘pressure’. Value marked as UNIT_UNKNOWN.</li><li>Field ‘productionRate’ (last) exceeds model boundary (100).</li></ul></div><span className="ml-auto h-fit rounded border border-primary/30 px-2 py-1 text-[6px]">6 more ...</span></div></section>
    <section className="rounded-md border border-border bg-card p-2 shadow-sm"><div className="flex items-center"><h2 className="flex items-center gap-2 text-[9px] font-bold"><Activity className="h-4 w-4 text-violet-foreground" />Synchronized Twin/Pipeline Preview (Record #{record + 1} / 5)</h2><div className="ml-auto flex gap-2"><Button variant="outline" className="h-6 text-[7px]" onClick={() => setRecord(0)}><RefreshCw />Reset</Button><Button className="h-6 bg-mint-foreground text-[7px] text-primary-foreground" onClick={() => setRecord((record + 1) % payloads.length)}>▶ Step Next</Button></div></div><div className="mt-2 grid grid-cols-6 gap-2"><AuditMetric icon={CalendarDays} label="Timestamp" value={String(current.timestamp).slice(0, 19)} tone="bg-sky-soft text-sky-foreground" /><AuditMetric icon={Thermometer} label="Reservoir temp" value={`${current.reservoirTemperature} °C`} tone="bg-mint text-mint-foreground" /><AuditMetric icon={Droplet} label="Oil viscosity" value="500.3 cP" tone="bg-violet-soft text-violet-foreground" /><AuditMetric icon={Waves} label="Production rate" value="5.72 BOPD" tone="bg-sky-soft text-sky-foreground" /><AuditMetric icon={Zap} label="SRP load index" value="52.1%" tone="bg-amber-soft text-accent-foreground" /><AuditMetric icon={ShieldCheck} label="Risk level" value="LOW" tone="bg-rose-soft text-rose-foreground" /></div></section>
    <section className="overflow-hidden rounded-md border border-border bg-card p-2 shadow-sm"><h2 className="mb-2 flex items-center gap-2 text-[9px] font-bold"><Database className="h-4 w-4 text-sky-foreground" />Normalised Ingested Records (5)</h2><div className="grid grid-cols-[34px_145px_70px_90px_115px_repeat(6,1fr)] bg-muted px-2 py-1 text-[6px] font-bold uppercase text-muted-foreground"><span>#</span><span>Timestamp</span><span>Well</span><span>Source</span><span>Status</span><span>Temp (°C)</span><span>Visc (cP)</span><span>GPR</span><span>Stroke (m)</span><span>Steam (T/d)</span><span>Pres (bar)</span></div>{sampleRows.map((row) => <div key={row[0]} className="grid grid-cols-[34px_145px_70px_90px_115px_repeat(6,1fr)] border-t border-border px-2 py-1 text-[6px]">{row.map((cell, i) => <span key={`${cell}-${i}`} className={i === 4 ? "w-fit rounded border border-primary bg-amber-soft px-1 font-bold text-accent-foreground" : i >= 5 ? "font-semibold text-mint-foreground" : ""}>{cell}</span>)}</div>)}</section>
  </main></div></div></div>;
}

export default DataExplorerPage;
