import type { DeploymentGate } from './types';

export const MANDATORY_DEPLOYMENT_DISCLAIMER =
  'Antigravity Engineering Digital Twin — Decision support only — no automatic field actuation.';

export const TOTAL_VERIFIED_SIMULATION_TESTS_DEPLOYMENT = 304;

export const DEFAULT_DEPLOYMENT_GATES: DeploymentGate[] = [
  {
    gateId: 'GATE-01',
    category: 'CODE_INTEGRITY',
    name: 'Build Integrity & Bundler Check',
    status: 'PASS',
    severity: 'CRITICAL',
    evidence: '0 TypeScript errors, clean Vite build bundle generated.',
    limitation: 'Requires continuous CI integration.',
    requiredAction: 'Maintain clean build pipeline on changes.',
  },
  {
    gateId: 'GATE-02',
    category: 'TEST_INTEGRITY',
    name: 'Simulation Regression Suite',
    status: 'PASS',
    severity: 'CRITICAL',
    evidence: 'All 304 physics & engine unit tests passing deterministically.',
    limitation: 'Unit tests use mathematical physics formulations.',
    requiredAction: 'Re-run full suite on model updates.',
  },
  {
    gateId: 'GATE-03',
    category: 'PHYSICS_FOUNDATION',
    name: 'Thermal & Viscosity Coupled Physics',
    status: 'PASS',
    severity: 'CRITICAL',
    evidence: 'Coupled reservoir thermal conduction & log-linear viscosity model verified.',
    limitation: 'Calibrated for heavy-oil viscosity range (500–15,000 cP).',
    requiredAction: 'Flag out-of-bounds reservoir temperatures (>180°C).',
  },
  {
    gateId: 'GATE-04',
    category: 'HISTORICAL_VALIDATION',
    name: 'Historical Backtest & Performance Engine',
    status: 'PASS',
    severity: 'HIGH',
    evidence: 'Validated against Baghewala historical production & appraisal dataset.',
    limitation: 'Historical data limited to appraisal well test records.',
    requiredAction: 'Expand historical dataset as field produces.',
  },
  {
    gateId: 'GATE-05',
    category: 'CALIBRATION',
    name: 'Parameter Calibration & Provenance Tracking',
    status: 'PASS',
    severity: 'HIGH',
    evidence: 'Supported parameters calibrated; unmeasured tagged INSUFFICIENT_DATA.',
    limitation: 'Unmeasured reservoir properties remain baseline defaults.',
    requiredAction: 'Conduct pressure transient analysis for reservoir permeability.',
  },
  {
    gateId: 'GATE-06',
    category: 'UNCERTAINTY',
    name: 'Monte Carlo Uncertainty Analysis',
    status: 'PASS',
    severity: 'HIGH',
    evidence: 'Latin Hypercube sampling computes P10/P50/P90 production distributions.',
    limitation: 'Assumes log-normal distribution for reservoir permeability.',
    requiredAction: 'Verify input parameter standard deviations.',
  },
  {
    gateId: 'GATE-07',
    category: 'FIELD_INTEGRATION',
    name: 'Field Data Ingestion & Unit Normalization',
    status: 'PASS',
    severity: 'HIGH',
    evidence: 'JSON/CSV ingestion, unit normalization, outlier detection active.',
    limitation: 'Processes static or replayed field data payloads.',
    requiredAction: 'Ensure sensor data complies with standardized units.',
  },
  {
    gateId: 'GATE-08',
    category: 'TELEMETRY_READINESS',
    name: 'Live Telemetry Connection Abstraction',
    status: 'WARNING',
    severity: 'HIGH',
    evidence: 'Simulated & appraisal telemetry validated; real SCADA feed disconnected.',
    limitation: 'Real SCADA telemetry feed not connected.',
    requiredAction: 'Configure SCADA API endpoints for live telemetry connection.',
  },
  {
    gateId: 'GATE-09',
    category: 'DATA_QUALITY',
    name: 'Data Quality & Missing Value Imputation',
    status: 'PASS',
    severity: 'MEDIUM',
    evidence: 'Data quality scoring engine evaluates completeness & flags outliers.',
    limitation: 'Missing essential metrics trigger REJECT_RECORD policy.',
    requiredAction: 'Maintain sensor health and calibration schedules.',
  },
  {
    gateId: 'GATE-10',
    category: 'DECISION_TRACE',
    name: 'Auditable Decision Traceability',
    status: 'PASS',
    severity: 'HIGH',
    evidence: '8-stage decision trace captures physics, uncertainty, and recommendations.',
    limitation: 'Trace stored in local simulation state.',
    requiredAction: 'Persist audit logs to central database server.',
  },
  {
    gateId: 'GATE-11',
    category: 'RISK_ADVISORY',
    name: 'AI Risk Advisory & Warning Engine',
    status: 'PASS',
    severity: 'HIGH',
    evidence: 'Multi-variable risk advisory evaluates SRP mechanical stress & CSS limits.',
    limitation: 'Risk score depends on accuracy of operating thresholds.',
    requiredAction: 'Periodically review structural load limits.',
  },
  {
    gateId: 'GATE-12',
    category: 'AUDIT_LOGGING',
    name: 'Chronological Event Audit Trail',
    status: 'PASS',
    severity: 'MEDIUM',
    evidence: 'Detailed audit trail records stage events, provenance, and warnings.',
    limitation: 'Audit events are generated in-memory per run.',
    requiredAction: 'Export audit reports prior to session reset.',
  },
  {
    gateId: 'GATE-13',
    category: 'OPERATOR_OVERSIGHT',
    name: 'Human Operator Advisory Review Interface',
    status: 'PASS',
    severity: 'CRITICAL',
    evidence: 'Command Center & Step Workspaces provide full human operator control.',
    limitation: 'Requires trained petroleum/production engineering oversight.',
    requiredAction: 'Ensure qualified operator conducts pre-pilot review.',
  },
  {
    gateId: 'GATE-14',
    category: 'SAFETY_GOVERNANCE',
    name: 'Safety Governance & Mandatory Disclaimers',
    status: 'PASS',
    severity: 'CRITICAL',
    evidence: 'Explicit advisory-only banners rendered on all control screens.',
    limitation: 'Advisory recommendations rely on operator verification.',
    requiredAction: 'Enforce written safety approval protocol.',
  },
  {
    gateId: 'GATE-15',
    category: 'ACTUATION_PROTECTION',
    name: 'Zero Automatic Field Equipment Actuation Protection',
    status: 'PASS',
    severity: 'CRITICAL',
    evidence: 'Strict architectural decoupling prevents any automated control signal output.',
    limitation: 'No direct hardware connection by design.',
    requiredAction: 'Retain manual field equipment operation mode.',
  },
];
