import type { DeploymentAuditEvent, TelemetryConnectionInfo, DataAcceptanceResult, ModelAcceptanceResult, SafetyGovernanceResult, DeploymentGate } from './types';

export function generateDeploymentAuditTrail(
  telemetry: TelemetryConnectionInfo,
  dataAcceptance: DataAcceptanceResult,
  modelAcceptance: ModelAcceptanceResult,
  safety: SafetyGovernanceResult,
  gates: DeploymentGate[]
): DeploymentAuditEvent[] {
  const timestamp = new Date().toISOString();

  const events: DeploymentAuditEvent[] = [
    {
      eventId: 'EVT-01',
      timestamp,
      stage: '1. TELEMETRY DATA SOURCE',
      inputProvenance: telemetry.provenance,
      component: 'telemetryConnectionEngine',
      status: telemetry.status === 'DISCONNECTED' ? 'WARNING' : 'PASS',
      summary: `Telemetry source: ${telemetry.connectionLabel}. Status: ${telemetry.status}.`,
      warnings: telemetry.status === 'DISCONNECTED' ? ['SCADA telemetry is disconnected.'] : [],
      limitations: telemetry.isSimulated ? ['Data source is simulated or appraisal based.'] : [],
    },
    {
      eventId: 'EVT-02',
      timestamp,
      stage: '2. DATA ACCEPTANCE & CLEANING',
      inputProvenance: dataAcceptance.provenance,
      component: 'dataAcceptanceEngine',
      status: dataAcceptance.status === 'REJECT' ? 'FAIL' : dataAcceptance.status === 'ACCEPT_WITH_WARNINGS' ? 'WARNING' : 'PASS',
      summary: dataAcceptance.summary,
      warnings: dataAcceptance.warnings,
      limitations: [],
    },
    {
      eventId: 'EVT-03',
      timestamp,
      stage: '3. UNIT NORMALIZATION & METADATA',
      inputProvenance: telemetry.provenance,
      component: 'fieldDataIntegration',
      status: 'PASS',
      summary: `Unit status: ${telemetry.unitStatus}. Verified standard SI and Oilfield metric units.`,
      warnings: [],
      limitations: [],
    },
    {
      eventId: 'EVT-04',
      timestamp,
      stage: '4. DATA QUALITY EVALUATION',
      inputProvenance: dataAcceptance.provenance,
      component: 'computeDataQualityReport',
      status: dataAcceptance.completenessPercent >= 80 ? 'PASS' : 'WARNING',
      summary: `Completeness: ${dataAcceptance.completenessPercent.toFixed(1)}%. Outlier count: ${dataAcceptance.outlierCount}.`,
      warnings: dataAcceptance.warnings,
      limitations: [],
    },
    {
      eventId: 'EVT-05',
      timestamp,
      stage: '5. PHYSICS MODEL EXECUTION',
      inputProvenance: telemetry.provenance,
      component: 'coupledPhysicsChain (Steps 4.3-4.6)',
      status: 'PASS',
      summary: 'Coupled thermal, viscosity, mobility, and production physics engines executed.',
      warnings: [],
      limitations: ['Calibrated heavy oil range (500 - 15,000 cP).'],
    },
    {
      eventId: 'EVT-06',
      timestamp,
      stage: '6. PARAMETER CALIBRATION FIT',
      inputProvenance: 'DERIVED',
      component: 'historicalCalibrationEngine',
      status: modelAcceptance.calibratedModelAvailable ? 'PASS' : 'WARNING',
      summary: `Model mode: ${modelAcceptance.modelMode}. Calibrated parameter state verified.`,
      warnings: modelAcceptance.calibratedModelAvailable ? [] : ['Operating under baseline uncalibrated mode.'],
      limitations: [],
    },
    {
      eventId: 'EVT-07',
      timestamp,
      stage: '7. MONTE CARLO UNCERTAINTY',
      inputProvenance: 'DERIVED',
      component: 'uncertaintyAnalysisEngine',
      status: modelAcceptance.uncertaintyWidthBopd > 0 ? 'PASS' : 'WARNING',
      summary: `Uncertainty width: ${modelAcceptance.uncertaintyWidthBopd.toFixed(1)} BOPD. Latin Hypercube sampled.`,
      warnings: [],
      limitations: ['Assumes log-normal distribution for reservoir permeability.'],
    },
    {
      eventId: 'EVT-08',
      timestamp,
      stage: '8. SCENARIO OPTIMIZATION',
      inputProvenance: 'DERIVED',
      component: 'scenarioOptimizationEngine',
      status: 'PASS',
      summary: 'Multi-objective Pareto trade-off optimization executed.',
      warnings: [],
      limitations: [],
    },
    {
      eventId: 'EVT-09',
      timestamp,
      stage: '9. AI RISK ADVISORY',
      inputProvenance: 'DERIVED',
      component: 'riskEngine',
      status: 'PASS',
      summary: 'Multi-variable operational risk advisory evaluated.',
      warnings: [],
      limitations: [],
    },
    {
      eventId: 'EVT-10',
      timestamp,
      stage: '10. 8-STAGE DECISION TRACE',
      inputProvenance: 'DERIVED',
      component: 'decisionTraceEngine',
      status: 'PASS',
      summary: 'Auditable decision trace generated across physics, uncertainty, and recommendations.',
      warnings: [],
      limitations: [],
    },
    {
      eventId: 'EVT-11',
      timestamp,
      stage: '11. HUMAN OPERATOR REVIEW & SAFETY',
      inputProvenance: 'DERIVED',
      component: 'safetyGovernanceEngine',
      status: safety.automaticActuationBlocked ? 'PASS' : 'FAIL',
      summary: safety.summary,
      warnings: safety.violations,
      limitations: ['Requires human operator review prior to field action.'],
    },
    {
      eventId: 'EVT-12',
      timestamp,
      stage: '12. DEPLOYMENT GATE VERIFICATION',
      inputProvenance: 'DERIVED',
      component: 'deploymentGateEngine',
      status: gates.some((g) => g.status === 'BLOCKED') ? 'FAIL' : gates.some((g) => g.status === 'WARNING') ? 'WARNING' : 'PASS',
      summary: `Evaluated ${gates.length} deployment gates. Passed: ${gates.filter((g) => g.status === 'PASS').length}.`,
      warnings: gates.filter((g) => g.status === 'WARNING').map((g) => `${g.name}: ${g.evidence}`),
      limitations: gates.filter((g) => g.status === 'BLOCKED').map((g) => `BLOCKED: ${g.name}`),
    },
  ];

  return events;
}
