export const INTEGRATED_VALIDATION_DISCLAIMER =
  'DECISION SUPPORT ONLY — NO AUTOMATIC FIELD ACTUATION. Recommendations generated by this Baghewala Digital Twin model are purely advisory and require human engineering review and field operator authorization before modifying equipment controls or operating parameters.';

export const UNCERTAINTY_WIDTH_THRESHOLDS = {
  narrowBopd: 3.0,
  moderateBopd: 8.0,
  wideBopd: 15.0,
};

export const CONFIDENCE_WEIGHTS = {
  dataQuality: 0.35,
  dataCoverage: 0.25,
  calibrationBonus: 0.15,
  uncertaintyPenalty: 0.15,
  sampleCountWeight: 0.10,
};

export const DEFAULT_ASSUMPTIONS = [
  'Jodhpur Sandstone formation permeability is assumed homogeneous at 2.5 Darcy unless core data overrides.',
  'Reservoir temperature heat capacity follows heavy crude thermal conduction dynamics.',
  'VFD motor efficiency and mechanical SRP rod dynamics remain within rated operational envelopes.',
  'CSS steam quality is assumed at 80% dry steam at top of perforation.',
];

export const DEFAULT_LIMITATIONS = [
  'Limited historical appraisal records available for deep reservoir calibration.',
  'Model validation reflects local Baghewala Heavy Oil properties (17° API, 450–10000+ cP).',
  'Uncertainty range reflects model input parameter sensitivity, not statistical field certification.',
  'Decision support recommendations are purely advisory and do not actuate physical field equipment.',
];
